### ISSUE TITLE
Nav bar on TOP

### ISSUE THREAD

**Issue by puneethkanna** [AbhinavChanduChenumalla/rejolt-vmeg#1]
There is a navbar on top, but there is a Home button, why is it there.
![image](https://user-images.githubusercontent.com/40000406/85230157-efdb7b80-b40b-11ea-9fc5-7cf532666755.png)

**Comment by puneethkanna** [comment]
We need to remove one of these

**Comment by puneethkanna** [comment]
I observed it is useful in the other pages, so in the single pages like Home and Contact pages it can be removed

**Comment by Akashmallareddy** [comment]
@puneethkanna It's just designed.....we will do later

**Comment by puneethkanna** [comment]
> @puneethkanna It's just designed.....we will do later

Yes, all the bugs are raised to issues and will be cleared one by one.

**Comment by Akashmallareddy** [comment]
@puneethkanna I didn't get your point......please be more elaborative.

**Comment by puneethkanna** [comment]
> @puneethkanna I didn't get your point......please be more elaborative.

You have mentioned that we have just designed, we will resolve it later..

What I am saying is, we will raise issues of any kind of bugs and then fix one by one.

**Comment by Akashmallareddy** [comment]
Done

**Comment by puneethkanna** [comment]
It is not changed, please push the changes and then close the issue.

**Comment by Akashmallareddy** [comment]
Updated
