### ISSUE TITLE
Team card Height is more

### ISSUE THREAD

**Issue by puneethkanna** [AbhinavChanduChenumalla/rejolt-vmeg#2]
The first Team card height is more than others

**Comment by puneethkanna** [comment]
Need to change the pictures also

**Comment by Akashmallareddy** [comment]
@puneethkanna @AbhinavChanduChenumalla I didn't find any bug......all are same in height. 
we need to change pics.....send to Abhinav email

**Comment by puneethkanna** [comment]
![image](https://user-images.githubusercontent.com/40000406/85232339-d3473f80-b41b-11ea-8cc4-1fe22f4af17e.png)

**Comment by puneethkanna** [comment]
The height of the 1st card is more

**Comment by Akashmallareddy** [comment]
@puneethkanna I think it might be browser fault!! I cant see this uneven height in my lappy or mobile. What to do?

**Comment by puneethkanna** [comment]
Once check with the firefox in your browser, I will check with chrome in linux..

**Comment by puneethkanna** [comment]
I had checked with chrome linux, it is fine. Once check with the Firefox windows and update.

**Comment by Akashmallareddy** [comment]
I checked in firefox....its fine

**Comment by Akashmallareddy** [comment]
Done
